import { useEffect, useState } from "react";
import { getChatAttachmentUrl } from "../services/attachmentService";

function GeneratedImageContent({ image, compact = false }) {
  const [imageUrl, setImageUrl] = useState(image?.url || "");
  const [loadError, setLoadError] = useState("");

  useEffect(() => {
    let active = true;

    const loadImage = async () => {
      if (!image?.path) {
        setImageUrl(image?.url || "");
        return;
      }

      try {
        const signedUrl = await getChatAttachmentUrl(image.path);
        if (active) setImageUrl(signedUrl);
      } catch {
        if (active) setLoadError("The generated image could not be loaded.");
      }
    };

    loadImage();
    return () => {
      active = false;
    };
  }, [image?.path, image?.url]);

  if (loadError) {
    return <p className="text-sm text-red-300">{loadError}</p>;
  }

  if (!imageUrl) {
    return <p className="text-sm text-slate-400">Loading generated image…</p>;
  }

  return (
    <div className="space-y-3">
      <img
        src={imageUrl}
        alt={image?.name || "Image generated by Gemini"}
        className={`w-full rounded-xl border border-blue-200/[0.12] object-cover ${
          compact ? "aspect-video max-h-44" : "aspect-video max-h-[62vh]"
        }`}
      />

      {!compact && (
        <div className="flex flex-wrap gap-2">
          <a
            href={imageUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="rounded-lg border border-violet-400/25 bg-violet-500/10 px-3 py-2 text-sm font-semibold text-violet-200 transition hover:bg-violet-500/15"
          >
            Open full image
          </a>
          <a
            href={imageUrl}
            download={image?.name || "orbitalai-gemini-image.png"}
            className="rounded-lg border border-blue-200/[0.12] bg-white/[0.04] px-3 py-2 text-sm font-semibold text-slate-200 transition hover:bg-white/[0.07]"
          >
            Download
          </a>
        </div>
      )}
    </div>
  );
}

export default GeneratedImageContent;
