import { useEffect, useState } from "react";
import {
  downloadChatAttachment,
  getChatAttachmentUrl,
} from "../services/attachmentService";

const getDownloadName = (name) =>
  String(name || "orbitalai-openai-image.png")
    .replace(/[\\/:*?"<>|]+/g, "-")
    .trim() || "orbitalai-openai-image.png";

function GeneratedImageContent({ image, compact = false }) {
  const [imageUrl, setImageUrl] = useState(image?.url || "");
  const [loadError, setLoadError] = useState("");
  const [downloadError, setDownloadError] = useState("");
  const [isDownloading, setIsDownloading] = useState(false);

  useEffect(() => {
    let active = true;

    const loadImage = async () => {
      if (!image?.path) {
        setImageUrl(image?.url || "");
        return;
      }

      try {
        const signedUrl = await getChatAttachmentUrl(image.path);
        if (active) setImageUrl(signedUrl);
      } catch {
        if (active) setLoadError("The generated image could not be loaded.");
      }
    };

    loadImage();
    return () => {
      active = false;
    };
  }, [image?.path, image?.url]);

  const handleDownload = async () => {
    setIsDownloading(true);
    setDownloadError("");

    try {
      let blob;

      if (image?.path) {
        blob = await downloadChatAttachment(image.path);
      } else {
        const response = await fetch(imageUrl);
        if (!response.ok) throw new Error("Image download failed.");
        blob = await response.blob();
      }

      const objectUrl = URL.createObjectURL(blob);
      const downloadLink = document.createElement("a");
      downloadLink.href = objectUrl;
      downloadLink.download = getDownloadName(image?.name);
      document.body.appendChild(downloadLink);
      downloadLink.click();
      downloadLink.remove();
      window.setTimeout(() => URL.revokeObjectURL(objectUrl), 1000);
    } catch {
      setDownloadError(
        "The image could not be downloaded. Please try again in a moment.",
      );
    } finally {
      setIsDownloading(false);
    }
  };

  if (loadError) {
    return <p className="text-sm text-red-300">{loadError}</p>;
  }

  if (!imageUrl) {
    return <p className="text-sm text-slate-400">Loading generated image…</p>;
  }

  return (
    <div className="space-y-3">
      <img
        src={imageUrl}
        alt={image?.name || "Image generated by OpenAI"}
        onError={() => setLoadError("The generated image could not be loaded.")}
        className={`w-full rounded-xl border border-blue-200/[0.12] object-cover shadow-[0_18px_55px_rgba(16,47,120,0.2)] ${
          compact ? "aspect-video max-h-44" : "aspect-video max-h-[62vh]"
        }`}
      />

      {!compact && (
        <div className="space-y-2 pt-1">
          <div className="flex flex-wrap items-center gap-3">
            <a
              href={imageUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 rounded-xl border border-violet-300/30 bg-gradient-to-r from-violet-500/20 to-blue-500/15 px-4 py-2.5 text-sm font-semibold text-violet-100 shadow-[0_10px_28px_rgba(91,68,210,0.14)] transition hover:border-violet-300/50 hover:from-violet-500/30 hover:to-blue-500/25 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-300/70"
            >
              <span aria-hidden="true">↗</span>
              Open full image
            </a>
            <button
              type="button"
              onClick={handleDownload}
              disabled={isDownloading}
              className="inline-flex items-center gap-2 rounded-xl border border-blue-300/30 bg-gradient-to-r from-blue-600/90 to-violet-600/90 px-4 py-2.5 text-sm font-semibold text-white shadow-[0_10px_30px_rgba(53,86,255,0.22)] transition hover:brightness-110 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-300/70 disabled:cursor-wait disabled:opacity-60"
            >
              <span aria-hidden="true">↓</span>
              {isDownloading ? "Downloading…" : "Download image"}
            </button>
          </div>
          {downloadError && (
            <p role="alert" className="text-sm text-red-300">
              {downloadError}
            </p>
          )}
        </div>
      )}
    </div>
  );
}

export default GeneratedImageContent;
