create table if not exists public.api_usage_events (
  id bigint generated by default as identity primary key,
  user_id text not null,
  route text not null,
  created_at timestamptz not null default now()
);

create index if not exists api_usage_events_user_route_created_idx
  on public.api_usage_events (user_id, route, created_at desc);

alter table public.api_usage_events enable row level security;

revoke all on table public.api_usage_events from anon, authenticated;

create or replace function public.check_api_usage_window(
  p_user_id text,
  p_route text,
  p_minute_limit integer,
  p_window_limit integer,
  p_window_hours integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  minute_count integer;
  window_count integer;
  minute_first_at timestamptz;
  window_first_at timestamptz;
  window_interval interval;
begin
  if p_minute_limit < 1 or p_window_limit < 1 or p_window_hours < 1 then
    raise exception 'Usage limits must be positive';
  end if;

  window_interval := make_interval(hours => p_window_hours);

  perform pg_advisory_xact_lock(
    hashtextextended(p_user_id || ':' || p_route, 0)
  );

  delete from public.api_usage_events
  where user_id = p_user_id
    and route = p_route
    and created_at < now() - greatest(window_interval, interval '2 days');

  select
    count(*) filter (where created_at >= now() - interval '1 minute'),
    min(created_at) filter (where created_at >= now() - interval '1 minute'),
    count(*) filter (where created_at >= now() - window_interval),
    min(created_at) filter (where created_at >= now() - window_interval)
  into minute_count, minute_first_at, window_count, window_first_at
  from public.api_usage_events
  where user_id = p_user_id
    and route = p_route;

  if minute_count >= p_minute_limit then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'minute',
      'limit', p_minute_limit,
      'remaining', 0,
      'reset_at', minute_first_at + interval '1 minute',
      'window_hours', 0
    );
  end if;

  if window_count >= p_window_limit then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'window',
      'limit', p_window_limit,
      'remaining', 0,
      'reset_at', window_first_at + window_interval,
      'window_hours', p_window_hours
    );
  end if;

  insert into public.api_usage_events (user_id, route)
  values (p_user_id, p_route);

  return jsonb_build_object(
    'allowed', true,
    'reason', '',
    'limit', p_window_limit,
    'remaining', greatest(0, p_window_limit - window_count - 1),
    'reset_at', coalesce(window_first_at, now()) + window_interval,
    'window_hours', p_window_hours
  );
end;
$$;

revoke all on function public.check_api_usage_window(
  text,
  text,
  integer,
  integer,
  integer
) from public, anon, authenticated;

grant execute on function public.check_api_usage_window(
  text,
  text,
  integer,
  integer,
  integer
) to service_role;
