-- Complete persistence schema for the OrbitalAI workspace.
-- This migration is safe to run after an older, partial workspaces table.

create table if not exists public.workspaces (
  id bigint generated by default as identity primary key,
  user_id text not null,
  name text not null default 'My Workspace',
  chats jsonb not null default '[]'::jsonb,
  chat_messages jsonb not null default '{}'::jsonb,
  projects jsonb not null default '[]'::jsonb,
  project_chats jsonb not null default '{}'::jsonb,
  project_files jsonb not null default '{}'::jsonb,
  project_notes jsonb not null default '{}'::jsonb,
  selected_chat text not null default '',
  selected_project text not null default '',
  archived_chats jsonb not null default '[]'::jsonb,
  archived_projects jsonb not null default '[]'::jsonb,
  pinned_chats jsonb not null default '[]'::jsonb,
  chat_activity jsonb not null default '{}'::jsonb,
  activity_log jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.workspaces
  add column if not exists id bigint generated by default as identity,
  add column if not exists user_id text,
  add column if not exists name text default 'My Workspace',
  add column if not exists chats jsonb default '[]'::jsonb,
  add column if not exists chat_messages jsonb default '{}'::jsonb,
  add column if not exists projects jsonb default '[]'::jsonb,
  add column if not exists project_chats jsonb default '{}'::jsonb,
  add column if not exists project_files jsonb default '{}'::jsonb,
  add column if not exists project_notes jsonb default '{}'::jsonb,
  add column if not exists selected_chat text default '',
  add column if not exists selected_project text default '',
  add column if not exists archived_chats jsonb default '[]'::jsonb,
  add column if not exists archived_projects jsonb default '[]'::jsonb,
  add column if not exists pinned_chats jsonb default '[]'::jsonb,
  add column if not exists chat_activity jsonb default '{}'::jsonb,
  add column if not exists activity_log jsonb default '[]'::jsonb,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.workspaces
set
  name = coalesce(name, 'My Workspace'),
  chats = coalesce(chats, '[]'::jsonb),
  chat_messages = coalesce(chat_messages, '{}'::jsonb),
  projects = coalesce(projects, '[]'::jsonb),
  project_chats = coalesce(project_chats, '{}'::jsonb),
  project_files = coalesce(project_files, '{}'::jsonb),
  project_notes = coalesce(project_notes, '{}'::jsonb),
  selected_chat = coalesce(selected_chat, ''),
  selected_project = coalesce(selected_project, ''),
  archived_chats = coalesce(archived_chats, '[]'::jsonb),
  archived_projects = coalesce(archived_projects, '[]'::jsonb),
  pinned_chats = coalesce(pinned_chats, '[]'::jsonb),
  chat_activity = coalesce(chat_activity, '{}'::jsonb),
  activity_log = coalesce(activity_log, '[]'::jsonb),
  created_at = coalesce(created_at, now()),
  updated_at = coalesce(updated_at, now());

-- Keep the newest row if an older setup accidentally created duplicate
-- workspaces for the same Firebase user.
delete from public.workspaces older
using public.workspaces newer
where older.user_id = newer.user_id
  and (
    older.updated_at < newer.updated_at
    or (
      older.updated_at = newer.updated_at
      and older.ctid < newer.ctid
    )
  );

create unique index if not exists workspaces_user_id_unique_idx
  on public.workspaces (user_id);

create unique index if not exists workspaces_id_unique_idx
  on public.workspaces (id);

alter table public.workspaces
  alter column user_id set not null,
  alter column name set not null,
  alter column chats set not null,
  alter column chat_messages set not null,
  alter column projects set not null,
  alter column project_chats set not null,
  alter column project_files set not null,
  alter column project_notes set not null,
  alter column selected_chat set not null,
  alter column selected_project set not null,
  alter column archived_chats set not null,
  alter column archived_projects set not null,
  alter column pinned_chats set not null,
  alter column chat_activity set not null,
  alter column activity_log set not null,
  alter column created_at set not null,
  alter column updated_at set not null;

alter table public.workspaces enable row level security;
alter table public.workspaces force row level security;

grant select, insert, update, delete on public.workspaces
  to anon, authenticated;

do $$
declare
  workspace_sequence text;
begin
  workspace_sequence := pg_get_serial_sequence('public.workspaces', 'id');

  if workspace_sequence is not null then
    execute format(
      'grant usage, select on sequence %s to anon, authenticated',
      workspace_sequence
    );
  end if;
end;
$$;

drop policy if exists "Users manage only their workspace"
  on public.workspaces;
create policy "Users manage only their workspace"
  on public.workspaces
  for all
  to anon, authenticated
  using (
    user_id = (select auth.jwt() ->> 'sub')
  )
  with check (
    user_id = (select auth.jwt() ->> 'sub')
  );

-- Keep workspace file buckets private and reject unexpectedly large or
-- unsupported uploads before they reach an extraction function.
insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values
  (
    'orbital-attachments',
    'orbital-attachments',
    false,
    52428800,
    array[
      'application/pdf',
      'text/plain',
      'text/csv',
      'text/rtf',
      'application/rtf',
      'image/jpeg',
      'image/png',
      'image/webp',
      'image/gif',
      'application/msword',
      'application/vnd.ms-powerpoint',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.oasis.opendocument.text',
      'application/vnd.oasis.opendocument.spreadsheet',
      'application/vnd.oasis.opendocument.presentation'
    ]::text[]
  ),
  (
    'orbital-files',
    'orbital-files',
    false,
    52428800,
    array[
      'application/pdf',
      'text/plain',
      'text/csv',
      'text/rtf',
      'application/rtf',
      'image/jpeg',
      'image/png',
      'image/webp',
      'image/gif',
      'application/msword',
      'application/vnd.ms-powerpoint',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.oasis.opendocument.text',
      'application/vnd.oasis.opendocument.spreadsheet',
      'application/vnd.oasis.opendocument.presentation'
    ]::text[]
  )
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
