create table if not exists public.api_usage_events (
  id bigint generated by default as identity primary key,
  user_id text not null,
  route text not null,
  created_at timestamptz not null default now()
);

create index if not exists api_usage_events_user_route_created_idx
  on public.api_usage_events (user_id, route, created_at desc);

alter table public.api_usage_events enable row level security;

revoke all on table public.api_usage_events from anon, authenticated;

create or replace function public.check_api_rate_limit(
  p_user_id text,
  p_route text,
  p_minute_limit integer,
  p_daily_limit integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  minute_count integer;
  daily_count integer;
begin
  perform pg_advisory_xact_lock(
    hashtextextended(p_user_id || ':' || p_route, 0)
  );

  delete from public.api_usage_events
  where user_id = p_user_id
    and route = p_route
    and created_at < now() - interval '2 days';

  select
    count(*) filter (where created_at >= now() - interval '1 minute'),
    count(*) filter (where created_at >= now() - interval '1 day')
  into minute_count, daily_count
  from public.api_usage_events
  where user_id = p_user_id
    and route = p_route;

  if minute_count >= p_minute_limit or daily_count >= p_daily_limit then
    return false;
  end if;

  insert into public.api_usage_events (user_id, route)
  values (p_user_id, p_route);

  return true;
end;
$$;

revoke all on function public.check_api_rate_limit(text, text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.check_api_rate_limit(text, text, integer, integer)
  to service_role;
